#!/usr/bin/env python3

import gender_bias
import argparse

parser = argparse.ArgumentParser()
parser.add_argument('document', help="document to analyze")
parser.add_argument('-s', help="list sentences", action='store_true')
parser.add_argument('-w', help="list words", action='store_true')
parser.add_argument('-c', help="list categories", action='store_true')

if __name__ == "__main__":
    options = parser.parse_args()
    text = gender_bias.load_text(options.document)
    if options.s:
        print("\n".join(gender_bias.sentences_from_text(text)))
    if options.w:
        print(gender_bias.words_from_text(text))
    if options.c:
        for type, words in gender_bias.categorize(text).items():
            print(type, words)
