#!/usr/bin/env python3

from gender_bias import Document
import argparse

parser = argparse.ArgumentParser()
parser.add_argument('document', help="document to analyze")
parser.add_argument('-s', help="list sentences", action='store_true')
parser.add_argument('-w', help="list words", action='store_true')
parser.add_argument('-ws', help="list words (stemmed)", action='store_true')
parser.add_argument('-c', help="list categories", action='store_true')

if __name__ == "__main__":
    options = parser.parse_args()
    text = Document(options.document)
    if options.s:
        print("\n".join(text.sentences()))
    if options.w:
        print(text.words())
    if options.ws:
        print(text.stemmed_words())
    if options.c:
        for type, words in text.words_by_part_of_speech().items():
            print(type, words)
